packages:
  - .
  - ./markdown-schema
  - ./markdown-transformer
  - ./extension
  - ./landing

catalog:
  '@prosemirror-processor/markdown': ^0.0.1-alpha.4
  '@prosemirror-processor/unist': ^0.0.1-alpha.7
  prosekit: ^0.15.4
  prosemirror-inputrules: 1.5.0
  prosemirror-test-builder: ^1.1.1
  prosemirror-model: ^1.25.3
  prosemirror-state: ^1.4.3
  prosemirror-view: ^1.40.1
  prosemirror-commands: ^1.7.1
  remark-gfm: ^4.0.1
  solid-js: ^1.9.9
  statebuilder: ^0.8.1
  tsdown: ^0.14.2
  typescript: ^5.9.2
  vitest: ^3.2.4
  prettier: ^3.6.2
  '@tanstack/config': ^0.20.1
  '@types/node': ^24.3.1
  '@vitest/ui': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  "@types/mdast": ^4.0.4
  "@types/unist": ^3.0.3
  vite: ^7.1.4
  vite-plugin-solid: ^2.11.1
