packages:
  - .
  - ./markdown-schema
  - ./markdown-transformer
  - ./extension
  - ./landing

catalog:
  '@prosemirror-processor/markdown': ^0.0.1-alpha.3
  '@prosemirror-processor/unist': ^0.0.1-alpha.6
  prosekit: ^0.15.4
  prosemirror-inputrules: 1.5.0
  prosemirror-model: ^1.25.3
  prosemirror-state: ^1.4.3
  prosemirror-view: ^1.40.1
  remark-gfm: ^4.0.1
  solid-js: ^1.9.9
  statebuilder: ^0.8.1
  tsdown: ^0.14.2
  typescript: ^5.9.2
