on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: 游닌 Setup
        uses: ./.github/actions/setup-job
      - name: 游닌 Monorepo install
        uses: ./.github/actions/pnpm-install

  build:
    name: build-core
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: 游닌 Setup
        uses: ./.github/actions/setup-job
      - name: 游닌 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: |
          pnpm build:core-libs

  test:
    name: test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: 游닌 Setup
        uses: ./.github/actions/setup-job
      - name: 游닌 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Tests
        run: |
          pnpm --filter ./markdown-schema --filter ./ run test

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true